server:
  port: 8769
spring:
  application:
    name: config
  cloud:
    config:
      uri: http://localhost:8769
      profile: default
      label: master
      server:
        git:
          uri: https://gitee.com/jiaotuT/config-repo-demo.git
          username: 17621788073
          password: aq13639166641
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
